Repository fluid-project/floeproject.org, pull requests merged in 2020-09, with the labels that each got.

#112 Add AT template in technical details section of bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#197 fix: resolve Markdown linting error
  src/news/2020-08-28-SNOW-OER.md
Labels: bug

#199 feat: automatically generate news list on homepage
  .eleventy.js
  src/_includes/layouts/default.njk
  src/_includes/layouts/newsindex.njk
  src/_includes/layouts/post.njk
  src/filters/limit-filter.js
  src/index.html
  src/news/news.json
  src/newsindex.md
Labels: enhancement
